; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
build_flags = -D LED_BUILTIN=2
monitor_speed = 115200
lib_deps =
  Wire@1.0.1
  Adafruit GFX Library@1.10.14
  Adafruit BusIO@1.11.3 
  GxEPD2@1.4.5
  Adafruit STMPE610@1.1.4
  ESP_WiFiManager@1.10.2
  ESP_DoubleResetDetector@1.3.1
  arduino-libraries/NTPClient@3.1.0
